### PR TITLE
404 page edited

### PR DESCRIPTION
**Pull request by PROTechThor**
HTML and styling added

### CODE REVIEW

**Comment by PROTechThor** [comment]
@evanwaltersdev Please clarify. You mean I should add outside fonts from an API? Or should I change the current fonts used?

**Comment by evanwaltersdev** [comment]
@PROTechThor 
We have been using futura from google fonts

**Comment by PROTechThor** [comment]
I suppose I should use that too? Got it.

**Comment by unixfy** [comment]
You should also serve that image file locally instead of from another website.

**Comment by PROTechThor** [comment]
Either I can't seem to link the actual futura font, or it doesn't look right to be.

**Comment by unixfy** [comment]
> Either I can't seem to link the actual futura font, or it doesn't look right to be.

You are right, this is our fault. The Futura font isn't free and currently isn't linked via CSS so its displaying properly depends on whether each client has the font installed. I'm working on moving everything to a free font (Oswald), please keep an eye on #51, thanks!

In the meantime, it would be nice if you can implement the header/footer from index.html and serve the dinosaur image locally.

**Comment by unixfy** [comment]
Unfortunately, the person who called dibs on the 404 has already submitted a 404 page which has already been merged. This means that your changes will not be merged into this repo :(

However, definitely keep contributing to this repo and the OSS community as a whole :)

**Pull request closed without merging**
